name: Feature Request
description: Request a new feature
labels: ["kind:feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem does this solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the solution you would like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
    validations:
      required: false
